// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgprsyoqhvnpmvlxjefa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBncHJzeW9xaHZucG12bHhqZWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMTI0MjYsImV4cCI6MjA1NTg4ODQyNn0.j93PPAAEml0E0IucE3ET0VkisidNCYEdM1GQgrJB6cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);